### ISSUE TITLE
Initiate Unit Testing for Sprint 4

### ISSUE THREAD

**Issue by prafulnair** [hemareddy123/ProjectK-Soen6011summer2023#105]
**Description**
The objective of this task is to initiate and develop unit tests for some of the features for the upcoming sprint (Sprint 4). The tests will be focusing on 1 or 2 core features (and their sub-features). 
The objective of this task is to identify critical units and functionalities within the application and create a suite of automated unit tests to verify their behaviour. By doing so, we aim to detect and resolve bugs early in the development process, enhance code quality, and establish a solid foundation for continuous integration and delivery.

**Comment by himi98** [comment]
The unit tests for Sign up/Registration, Login/Authentication, and Post a job functionalities has been initiated and conducted successfully. Hence, closing this issue.
