### ISSUE TITLE
TASK| Implement the UI for removing users (student and employer) for the admin user in their dashboard

### ISSUE THREAD

**Issue by prafulnair** [hemareddy123/ProjectK-Soen6011summer2023#119]
**Description**
Design and implement a simple UI and place it in the dashboard for the admin dashboard so that the admin can efficiently control users, and remove them if needed. Such a feature is required when users are reported by people, or when an unauthorized employer user is on the system.

Design can be simple, minimal, and at the same time is intuitive and completes the required functionality.

**Comment by 005Dikshant** [comment]
Task has been implemented
