### ISSUE TITLE
CI/CD building and testing 

### ISSUE THREAD

**Issue by prafulnair** [hemareddy123/ProjectK-Soen6011summer2023#129]
**Description**
This is the continuation of the previous sprint's CI/CD work. This task involves setting up an efficient CI/CD system for our project. This system will make our development work easier, improve the quality of our code, and make it simpler to deploy changes to the final product. It's essential for speeding up our work, automating testing, and encouraging better teamwork among all contributors.

**Comment by himi98** [comment]
CI build and testing has been completed and implemented successfully. Hence, closing this issue.
