### ISSUE TITLE
Development of Login Module Back-end

### ISSUE THREAD

**Issue by prafulnair** [hemareddy123/ProjectK-Soen6011summer2023#48]
**Description**
The template issue by front end team can be used/modified by the back-end team to complete the user login module. This also involves a registration page.

**Technical Guidelines** 
As per our last discussion, the team may continue the use of Python with Flask, along with Sqlite for the database

**Assignee**
Dikshant and Himanshu

**Comment by himi98** [comment]
We have implemented the login and register of each type of usereither as admin, employer or student securely with password to be stored in database in hashed format. 
Reference user stories:- #4 and #7
