### ISSUE TITLE
Development of Add a Job UI

### ISSUE THREAD

**Issue by prafulnair** [hemareddy123/ProjectK-Soen6011summer2023#50]
**Description** 
The front end team has to issue some template for an Employer feature : add a job. Here the Employer can specify job details like title, date, location, skills needed etc and publish this job. The template can be modified as per back-end teams need. 

**Technical Guidelines**:
Use of HTML, CSS and JS along with JS or Ajax if needed.

**Assignee**:
Praful and Tanay (and Back-end team for further modification)

**Comment by prafulnair** [comment]
A basic template had been issued by Praful and Tanay for the back-end team to work on/modify. They have succesfully made all the required changes. Closing this issue now.

**Comment by 005Dikshant** [comment]
We have successfully created UI for job cards posted when an employer creates a job posting, and multiple job cards can sit beside each other with no overlaps. 
Reference commit - #6
