### ISSUE TITLE
Development of Employer Dashboard + Add a job Backend

### ISSUE THREAD

**Issue by prafulnair** [hemareddy123/ProjectK-Soen6011summer2023#51]
**Description** 
The backend team needs to develop the database and the backend structure of this module. The database will contain table containing information regarding the job posted , like title, location etc. 

**Technical Guidelines**:
Python, Flask, Sqlite

**Assignee**:
Dikshant and Himanshu

**Comment by 005Dikshant** [comment]
We have implemented the job posting on the front end and as well as on the back end, and each of the job postings contains the title, location and posted as mandatory fields.
