### ISSUE TITLE
Develop View and Select Candidates Feature

### ISSUE THREAD

**Issue by prafulnair** [hemareddy123/ProjectK-Soen6011summer2023#54]
**Description** 
This feature will allow Employers to browse candidates and select candidates who have applied for a particular job

**Technology Guidelines**:
Python, Flask, HTML, CSS, JavaScript, SQLite

**Assignee**
Dikshant

**Comment by himi98** [comment]
Employer can view selected candidates that have applied for a job vacancy and can select the required candidates for job interview
Reference user story :  #12
