### ISSUE TITLE
Post a Job Vacancy

### ISSUE THREAD

**Issue by hemareddy123** [hemareddy123/ProjectK-Soen6011summer2023#6]
This feature deals with posting a job advertisement from employer.

**Comment by himi98** [comment]
The epic and user stories related to this issue were created and added successfully to the [user_stories_Sprint1.md](https://github.com/hemareddy123/ProjectK-Soen6011summer2023/blob/main/Sprint%201/user_stories_Sprint1.md) file. Hence, closing the issue.
