### ISSUE TITLE
Student Profile Creation

### ISSUE THREAD

**Issue by prafulnair** [hemareddy123/ProjectK-Soen6011summer2023#61]
**Decription**
We aim to develop a feature where the user: students can create a profile/resume for their job application.

**Sprint** : This issue is for Sprint 3. 
**Assignee**: 
This will be updated shortly after next meeting and its discussion.

**Comment by 005Dikshant** [comment]
Created student profile in the backend as of now, will implement the profile to integrate with front-end in sprint-3

**Comment by prafulnair** [comment]
Uploading a basic UI (html, css and Js) for the backend team to work with

**Comment by 005Dikshant** [comment]
student profile integrated from both front-end and backend successfully implemented
