### ISSUE TITLE
Student Applying for a Job Feature

### ISSUE THREAD

**Issue by prafulnair** [hemareddy123/ProjectK-Soen6011summer2023#62]
**Description**
We aim to build a feature for students/job-seekers where they can _**search and apply**_ for the jobs posted by employers.

**Sprint**: This issue is for Sprint 3

**Assignee**:  Dikshant, Himanshu and Revanth

**Comment by 005Dikshant** [comment]
Students can apply for the jobs posted by any of the employers and can view the details like the description or start and end date of the job posted. The feature has been implemented as per requirement, thus closing it
