### ISSUE TITLE
TASK | Admin Feature of Tracking all user profiles

### ISSUE THREAD

**Issue by prafulnair** [hemareddy123/ProjectK-Soen6011summer2023#70]
The admin will be given the unique privilege feature of viewing all the users of the platform. This would include all the employers and the students who have created an account in the platform. This tasks include creation of a dashboard for the admin as well as integrating this feature in that dashboard

**Comment by 005Dikshant** [comment]
Admin can track/view all the user profiles present in the system and perform a deletion action if required and this has been integrated in the dashboard of the admin. Thus closing it after successful implementation.
