### ISSUE TITLE
TASK | Admin Managing and tracking all Job postings

### ISSUE THREAD

**Issue by prafulnair** [hemareddy123/ProjectK-Soen6011summer2023#71]
This is a feature for admin users which will allow them to manage, track and view all the job posting posted by all the employers who have created the account in the platform and has posted job openings.

**Comment by 005Dikshant** [comment]
Admin can view the job posting posted by the employers and delete it if required this is updated on employer's dashboard and student dashboard as well, and students who applied for those jobs are automatically removed from the applied students of that employer. So hence feature is complete and closing it.
