### ISSUE TITLE
View Created Student Profile

### ISSUE THREAD

**Issue by prafulnair** [hemareddy123/ProjectK-Soen6011summer2023#80]
**Description**
Once the student creates a profile for themselves, they should be able to see it on the platform.  This could be as simple as viewing the information simply on the webpage. They should have an option to edit that information.

**Assignee**
Dikshant, Himanshu

**Comment by 005Dikshant** [comment]
The student profile is visible to the student, employers, and admin. So the feature is complete and therefore closing it
