### ISSUE TITLE
Student Dashboard

### ISSUE THREAD

**Issue by prafulnair** [hemareddy123/ProjectK-Soen6011summer2023#81]
**Description**
Once the student securely logs onto the platform, they should get a dashboard interface which would house all the features made available to a student user. They should be able to access features like 'create my profile', 'build resume', 'upload resume', 'search for jobs', 'view applied jobs' etc. from this dashboard. 

**Assignee**
Praful can help with UI as needed by backend team. Himanshu and Dikshant will be working on the API, database and the backend.

**Comment by 005Dikshant** [comment]
The student dashboard has a set the features including building the resume, uploading the resume, viewing of the profile, viewing all the posted jobs, and viewing the applied jobs with their states after selection. Thus feature is complete and closing it.
