### ISSUE TITLE
TASK | Create the backend REST API to fetch profile info to display. 

### ISSUE THREAD

**Issue by prafulnair** [hemareddy123/ProjectK-Soen6011summer2023#83]
**Description**
The backend team is tasked to create the REST API. We need to develop a backend REST API that will serve as the data source for fetching user profile information. This API will be responsible for providing the necessary data required to display user profiles on the front end.

**Comment by 005Dikshant** [comment]
The API has been developed that fetches the user information and displays the required information as per the user's role.
Therefore closing the issue
