### ISSUE TITLE
TASK | Create backend REST API to fetch all job postings by employers.

### ISSUE THREAD

**Issue by prafulnair** [hemareddy123/ProjectK-Soen6011summer2023#85]
**Description**
Develop a backend REST API that will facilitate retrieving all job postings submitted by employers. This API will enable the front end to display a comprehensive list of job opportunities available on our platform.

**Comment by 005Dikshant** [comment]
Admin and student dashboards have the functionality to view all the jobs posted by the employers and apply and delete options respectively with each job posting. Thus it has been completed and hence closing the issue.
