### ISSUE TITLE
TASK | Design and Implement "Apply to Job" Functionality UI on Student Dashboard (For Student Users)

### ISSUE THREAD

**Issue by prafulnair** [hemareddy123/ProjectK-Soen6011summer2023#90]
**Description**
This issue focuses on designing and implementing the "Apply to Job" functionality on the student dashboard. The primary goal is to create an intuitive interface that allows students to apply for job openings seamlessly. Kindly refer to issue #84 regarding integrating this feature on the dashboard for the student users. 
Once this issue is successfully addressed, students will be able to easily apply for job opportunities directly from their dashboard, streamlining the job application process and enhancing their overall experience on the platform. Let's collaborate to deliver a smooth and efficient "Apply to Job" functionality for our users.

I would request the backend team to update me regarding the progress of this task so that I can manage and handle the documentation work.

**Comment by 005Dikshant** [comment]
Students can apply for the job posted by employers. Thus it has been developed and closing it
