### ISSUE TITLE
TASK | Create Backend REST API for Modifying Student  (For Student User)

### ISSUE THREAD

**Issue by prafulnair** [hemareddy123/ProjectK-Soen6011summer2023#91]
**Description**
---
This task is related to issue #90. This involves the backend work and API testing for reflecting changes to the database when a student applies to a certain job. By implementing this API, we can support a seamless user experience and ensure that updated profile information is utilized when applying for job opportunities. Let's focus on efficiently implementing this crucial backend functionality.

**Comment by himi98** [comment]
We have successfully implemented the Modify Student feature. Hence, closing this issue.
