### ISSUE TITLE
TASK | Design and Implement "View Applied Jobs" UI on Student Dashboard

### ISSUE THREAD

**Issue by prafulnair** [hemareddy123/ProjectK-Soen6011summer2023#93]
**Description**
---
This issue aims to design and implement the "View Applied Jobs" user interface (UI) on the student dashboard. The feature will allow students to easily access and review a list of jobs they have applied for. The UI should be simple but intuitive, responsive, and seamlessly integrated into the existing dashboard (refer to issue#84), providing a positive user experience. Let's collaborate on delivering this valuable addition to enhance the student dashboard's functionality.

Thank you

**Comment by himi98** [comment]
The Student Dashboard UI was designed and implemented successfully. The backend api developed for #94 is being utilized here to display the applied jobs on the dashboard. Hence, closing this issue.
