### ISSUE TITLE
TASK |  Create Backend REST API for Fetching Applied Jobs by Students

### ISSUE THREAD

**Issue by prafulnair** [hemareddy123/ProjectK-Soen6011summer2023#94]
**Description**
----
This issue involves the development of a backend REST API to retrieve applied jobs by students. The API should enable efficient access to the list of jobs that individual students have applied for. By implementing this API, we can provide the necessary data for the "View Applied Jobs" feature on the student dashboard. Please refer to issue #93 for this task.

**Comment by himi98** [comment]
The feature and corresponding backend REST api for fetching applied jobs by students has been developed successfully. Hence, closing this issue.
