### ISSUE TITLE
TASK | Design UI for student profile creation

### ISSUE THREAD

**Issue by prafulnair** [hemareddy123/ProjectK-Soen6011summer2023#99]
**Description**
---
Upon successful login, the student users can click on the 'create profile' feature available on the dashboard to create and save a new profile. This task focuses on the creation of UI for such a feature, which will be fundamentally a form, saving user data into the database.
Please make sure that you can integrate this functionality into the user dashboard (for students) once it is completed. For this, refer to issue #84

**Comment by 005Dikshant** [comment]
Student profile UI has been developed and viewed by the student, employer, and admin. Therefore the feature is complete and therefore closing it
